import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/sections/header/MainHeader";
import TopFooter from "@/sections/header/TopFooter";
import Footer from "@/sections/footer/Footer";
import ProductContextApp from "@/components/ProductContextApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <ProductContextApp>
          <TopFooter></TopFooter>
          <MainHeader></MainHeader>
          {children}
          <Footer></Footer>
      </ProductContextApp>
      </body>
    </html>
  );
}
